CREATE DATABASE SENAI_ROMAN_DESAFIO_MATILHA

USE SENAI_ROMAN_DESAFIO_MATILHA

CREATE TABLE TIPO_USUARIO (
	ID INT IDENTITY  PRIMARY KEY NOT NULL
	,TIPO VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE TEMAS (
	ID INT IDENTITY  PRIMARY KEY NOT NULL
	,TEMA VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE USUARIOS (
	ID INT IDENTITY PRIMARY KEY NOT NULL
	,ID_TIPOUSUARIO INT FOREIGN KEY REFERENCES TIPO_USUARIO(ID) NOT NULL
	,NOME VARCHAR(255) NOT NULL
	,EMAIL VARCHAR(255) NOT NULL UNIQUE
	,SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE PROJETOS (
	ID INT IDENTITY PRIMARY KEY NOT NULL
	,NOME VARCHAR(255) NOT NULL
	,ID_TEMA INT FOREIGN KEY REFERENCES TEMAS(ID) NOT NULL
	,DESCRICAO VARCHAR(255) NOT NULL
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID) NOT NULL
);